name: Check if working

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  frontend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: movie-frontend/package-lock.json
      - run: npm ci
        working-directory: ./movie-frontend
      - run: npm run build --if-present
        working-directory: ./movie-frontend
      - run: npm start &
        working-directory: ./movie-frontend

      - name: Set up Java version for backend
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Build backend
        run: mvn spring-boot:run
        working-directory: ./movie-backend
    
      - name: Set up Java version for tests
        uses: actions/setup-java@v1
        with:
          java-version: '21'

      - name: Build and test with Maven
        run: mvn clean test
        working-directory: ./selenium-tests

      # - name: GitHub Action to create an Azure DevOps Bug Workitem when a workflow fails
      #   uses: stefanstranger/azuredevops-bug-action@1.1
      #   if: failure()
      #   with:
      #     OrganizationName: "01169606"
      #     PAT: "PAT"
      #     ProjectName: "MWO-project"
      #     AreaPath: "MWO-project"
      #     IterationPath: "MWO-project"
      #     GithubToken: "GithubToken"
      #     WorkflowFileName: "node.js.yml"
      #   env:
      #     PAT: ${{ secrets.PAT}}
      #     GithubToken: ${{ secrets.githubtoken}}
